name: "aws-deployment"

on: 
  push: 
   branches:
    - main


jobs: 
  dockerfile:
    runs-on: ubuntu
    name: "firstdeploy"
    steps:
      - name: 'gitclone'
        uses: actions/checkout@v4
      
      - name: 'gitupdate'
        run:  sudo apt-get update
      
      - name: 'docker build'
        run: docker build -t public.ecr.aws/m9n8x5g7/ankit-docker-project/firstproject:latest .
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
    
      - name: 'docker_push'
        run: docker push public.ecr.aws/m9n8x5g7/ankit-docker-project/firstproject:latest
 
 
